Resources:
  Benchmark:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs8.10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: Any